name: kiss_datastore
description: A simple, abstract datastore interface for Dart with an in-memory implementation for testing and development.
version: 0.1.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0


dependencies:
  very_good_analysis: ^9.0.0


dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
